module ApplicationHelper

	def active?(path)
		"active" if current_page?(path) # returns True if the current request URI was generated by the given options.
	end
	def admin_types
      ['AdminUser']
  end
end
